import React, { useState } from 'react'
import './TryByteNimbus.css'

export default function TryByteNimbus() {
  const [isGenerating, setIsGenerating] = useState(false)
  const [topic, setTopic] = useState('')
  const [generatedContent, setGeneratedContent] = useState('')

  const handleGenerate = async (e) => {
    e.preventDefault()
    if (!topic.trim()) return

    setIsGenerating(true)
    
    // Simulate AI generation with a realistic delay
    setTimeout(() => {
      setGeneratedContent(`
# ${topic} - Microlearning Module

## Learning Objectives
By the end of this module, you will be able to:
- Understand the core concepts of ${topic}
- Apply ${topic} principles in real-world scenarios
- Evaluate different approaches to ${topic}

## Key Concepts
- **Foundation**: Essential ${topic} principles
- **Application**: How to implement ${topic} effectively
- **Best Practices**: Proven strategies for success

## Interactive Elements
- Quick knowledge check
- Scenario-based learning
- Practical exercises

## Assessment
- Pre-learning quiz
- Post-module evaluation
- Skill demonstration

*Generated by ByteNimbus AI - Following ADDIE framework and Bloom's Taxonomy*
      `)
      setIsGenerating(false)
    }, 2000)
  }

  return (
    <section id="try" className="container-narrow py-20 relative try-bytenimbus-section">
      <div className="text-center mb-12">
        <h2 className="text-3xl md:text-4xl font-semibold tracking-tight mb-4">
          Try ByteNimbus
        </h2>
        <p className="text-white/70 max-w-2xl mx-auto">
          Experience the power of AI-assisted instructional design. Enter any topic and watch ByteNimbus create a complete microlearning module.
        </p>
      </div>

      <div className="nimbus-card p-8">
        <form onSubmit={handleGenerate} className="mb-8">
          <div className="flex flex-col md:flex-row gap-4 items-end">
            <div className="flex-1">
              <label htmlFor="topic" className="block text-sm font-medium text-white/80 mb-2">
                What would you like to learn about?
              </label>
              <input
                type="text"
                id="topic"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="e.g., Project Management, Digital Marketing, Python Programming..."
                className="w-full px-4 py-3 rounded-xl bg-white/10 border border-white/20 focus:outline-none focus:border-white/40 text-white placeholder-white/50"
                required
              />
            </div>
            <button
              type="submit"
              disabled={isGenerating}
              className="px-8 py-3 rounded-xl bg-white text-black font-medium hover:opacity-90 transition hover:scale-105 transform duration-200 shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none"
            >
              {isGenerating ? (
                <div className="flex items-center gap-2">
                  <div className="w-4 h-4 border-2 border-black/20 border-t-black rounded-full animate-spin"></div>
                  Generating...
                </div>
              ) : (
                'Generate Module'
              )}
            </button>
          </div>
        </form>

        {generatedContent && (
          <div className="mt-8 p-6 rounded-xl bg-white/5 border border-white/10">
            <div className="flex items-center gap-2 mb-4">
              <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div>
              <span className="text-sm font-medium text-green-400">AI-Generated Content</span>
            </div>
            <div className="prose prose-invert max-w-none">
              <pre className="whitespace-pre-wrap text-white/90 text-sm leading-relaxed">
                {generatedContent}
              </pre>
            </div>
            <div className="mt-4 flex gap-3">
              <button className="px-4 py-2 rounded-lg bg-white/10 border border-white/20 hover:bg-white/20 transition text-sm">
                Export as PDF
              </button>
              <button className="px-4 py-2 rounded-lg bg-white/10 border border-white/20 hover:bg-white/20 transition text-sm">
                Share Module
              </button>
              <button 
                onClick={() => setGeneratedContent('')}
                className="px-4 py-2 rounded-lg bg-white/10 border border-white/20 hover:bg-white/20 transition text-sm"
              >
                Generate New
              </button>
            </div>
          </div>
        )}

        <div className="mt-8 text-center">
          <p className="text-xs text-white/50">
            This is a demo. The full ByteNimbus experience includes advanced AI features, 
            SCORM export, team collaboration, and integration with your LMS.
          </p>
        </div>
      </div>
    </section>
  )
}

